name: semantic_gen_example
description: Example app demonstrating semantic_gen integration.
publish_to: "none"
version: 0.2.0+1
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"
dependencies:
  flutter:
    sdk: flutter
  semantic_gen:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
