name: semantic_gen_example
description: Example app demonstrating semantic_gen integration.
publish_to: "none"
version: 0.2.1+1
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"
dependencies:
  flutter:
    sdk: flutter
  semantic_gen:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  build_test: ^3.3.3

flutter:
  uses-material-design: true
