name: flutter_test_tags_example
description: Example app demonstrating flutter_test_tags integration.
publish_to: "none"
version: 0.2.0+1
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_test_tags:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
